version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - ../.env
    command: sleep infinity
    
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ../docker/volumes/postgres:/var/lib/postgresql/data
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - ../.env
    # network_mode: service:app
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)j
    # Vscode can access ports within development container, so we don't need to set port in devcontainer.json

  redis:
    image: redis
    # network_mode: service:app
    restart: unless-stopped
    volumes:
      - ../docker/volumes/redis:/data